name: Build and Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Build wheels
      run: |
        python -m cibuildwheel

    - name: List files in directory
      run: ls -R
    
    - name: Upload wheelhouse artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse
      
    

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Twine
      run: |
        python -m pip install --upgrade pip
        python -m pip install twine
    
    - name: Download wheelhouse artifact
      uses: actions/download-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse
    
    - name: List files in directory
      run: ls -R

    - name: Publish to PyPI
      run: |
        python -m twine upload wheelhouse/*.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}